/**
 * Trips Data
 *
 * To add a new trip, copy one of the objects below and paste it at the
 * TOP of the TRIPS array (newest/soonest first), then fill in the fields.
 *
 * Fields reference:
 *   id          – unique kebab-case string, e.g. 'japan-2026-04'
 *   title       – trip name shown on the card, e.g. 'FAB Asia Tour 2026'
 *   destination – city/country label, e.g. 'Shanghai & Yokohama'
 *   region      – broad region for filtering, e.g. 'Asia' | 'Europe' | 'Americas'
 *   status      – 'upcoming' | 'ongoing' | 'past' | 'planning'
 *   startDate   – ISO date for sorting, e.g. '2026-03-27'
 *   endDate     – ISO date, e.g. '2026-04-13'
 *   displayDates – human-readable date range shown on the card
 *   description – short paragraph describing the trip and what the page covers
 *   link        – relative URL to the trip's detail page
 *   tags        – array of short tag strings, e.g. ['FaB', 'Tournament', 'Leisure']
 */

/**
 * FaB World Tour Events 2026
 *
 * All Calling, Pro Tour, National Championship and Worlds events from the
 * official Flesh and Blood World Tour calendar. Shown as info bars on the
 * calendar only (not shown as trip cards on the trips index page).
 * Source: https://fabtcg.com/organised-play/
 */
const FAB_WORLD_TOUR = [

  {
    id: 'pq-darmstadt-2026-03-21',
    title: 'Pro Quest – Darmstadt',
    destination: 'Darmstadt, Germany',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-03-21',
    endDate: '2026-03-21',
    displayDates: 'Mar 21, 2026',
    description: 'Pro Quest in Darmstadt (Classic Constructed).',
    link: null,
    reportId: 'pq-darmstadt-2026-03-21',
    tags: ['FaB', 'Pro Quest'],
  },

  {
    id: 'pq-mainz-2026-03-14',
    title: 'Pro Quest – Mainz',
    destination: 'Mainz, Germany',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-03-14',
    endDate: '2026-03-14',
    displayDates: 'Mar 14, 2026',
    description: 'Pro Quest in Mainz (Classic Constructed).',
    link: null,
    reportId: 'pq-mainz-2026-03-15',
    tags: ['FaB', 'Pro Quest'],
  },

  {
    id: 'fab-calling-akihabara-2026',
    title: 'Calling – Akihabara',
    destination: 'Tokyo, Japan',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-01-09',
    endDate: '2026-01-11',
    displayDates: 'Jan 9–11, 2026',
    description: 'The Calling + Battle Hardened + Super Armory in Tokyo\'s TCG hub, Akihabara.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-columbus-2026',
    title: 'Calling – Columbus',
    destination: 'Columbus, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-01-16',
    endDate: '2026-01-18',
    displayDates: 'Jan 16–18, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Greater Columbus Convention Center, Ohio.',
    link: 'https://fabtcg.com/organised-play/2026/calling-columbus/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-london-2026',
    title: 'Calling – London',
    destination: 'London, UK',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-02-06',
    endDate: '2026-02-08',
    displayDates: 'Feb 6–8, 2026',
    description: 'Compendium of Rathe World Premiere & Calling (Silver Age, $20K) at ExCeL London.',
    link: 'https://fabtcg.com/organised-play/2026/world-premiere-london/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-san-diego-2026',
    title: 'Calling – San Diego',
    destination: 'San Diego, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-02-13',
    endDate: '2026-02-15',
    displayDates: 'Feb 13–15, 2026',
    description: 'The Calling (Silver Age, $20K) at San Diego Convention Center, California.',
    link: 'https://fabtcg.com/organised-play/2026/calling-san-diego/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-montreal-2026',
    title: 'Calling – Montréal',
    destination: 'Montréal, Canada',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-02-27',
    endDate: '2026-03-01',
    displayDates: 'Feb 27–Mar 1, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Palais des congrès de Montréal.',
    link: 'https://fabtcg.com/organised-play/2026/calling-montreal-2/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-toulouse-2026',
    title: 'Calling – Toulouse',
    destination: 'Toulouse, France',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-03-06',
    endDate: '2026-03-08',
    displayDates: 'Mar 6–8, 2026',
    description: 'The Calling (Classic Constructed, $20K) at MEETT – Toulouse Métropole, France.',
    link: 'https://fabtcg.com/organised-play/2026/calling-toulouse/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-brisbane-2026',
    title: 'Calling – Brisbane',
    destination: 'Brisbane, Australia',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-03-13',
    endDate: '2026-03-15',
    displayDates: 'Mar 13–15, 2026',
    description: 'The Calling (Classic Constructed) at Brisbane Convention & Exhibition Centre, Australia.',
    link: 'https://fabtcg.com/organised-play/2026/calling-brisbane/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-memphis-2026',
    title: 'Calling – Memphis',
    destination: 'Memphis, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-03-20',
    endDate: '2026-03-22',
    displayDates: 'Mar 20–22, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Renasant Convention Center, Memphis, TN.',
    link: 'https://fabtcg.com/organised-play/2026/calling-memphis-2/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-pro-tour-yokohama-2026',
    title: 'Pro Tour – Yokohama',
    destination: 'Yokohama, Japan',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-04-09',
    endDate: '2026-04-12',
    displayDates: 'Apr 9–12, 2026',
    description: 'Pro Tour: Yokohama ($200K, Classic Constructed & Silver Age) + Calling ($20K) at Pacifico Yokohama.',
    link: 'https://fabtcg.com/organised-play/2026/pro-tour-yokohama/',
    prepId: 'pro-tour-yokohama-2026',
    reportId: 'pt-yokohama-2026',
    tags: ['FaB', 'Pro Tour', 'World Tour'],
  },

  {
    id: 'fab-showdown-yokohama-2026-04-12',
    title: 'Showdown – Yokohama',
    destination: 'Yokohama, Japan',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-04-12',
    endDate: '2026-04-12',
    displayDates: 'Apr 12, 2026',
    description: 'Sunday Showdown (Classic Constructed) at Pacifico Yokohama, following Pro Tour weekend.',
    link: 'https://fabtcg.com/organised-play/2026/pro-tour-yokohama/',
    reportId: 'showdown-yokohama-2026-04-12',
    tags: ['FaB', 'Showdown', 'World Tour'],
  },

  {
    id: 'fab-calling-rotterdam-2026',
    title: 'Calling – Rotterdam',
    destination: 'Rotterdam, Netherlands',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-04-24',
    endDate: '2026-04-26',
    displayDates: 'Apr 24–26, 2026',
    description: 'The Calling (Classic Constructed, $20K) + Silver Age Showdown at Rotterdam Ahoy.',
    link: 'https://fabtcg.com/organised-play/2026/calling-rotterdam/',
    tags: ['FaB', 'Calling', 'World Tour'],
    reportId: 'calling-rotterdam-2026',
  },

  {
    id: 'ruika-shanghai-2026-04-03',
    title: 'RUIKA Event – Shanghai',
    destination: 'Shanghai, China',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-04-03',
    endDate: '2026-04-03',
    displayDates: 'Apr 3, 2026',
    description: 'Small local tournament in Shanghai on the Friday before Calling Shanghai.',
    link: null,
    reportId: 'ruika-shanghai-2026-04-03',
    tags: ['FaB', 'RTN'],
  },

  {
    id: 'fab-calling-shanghai-2026',
    title: 'Calling – Shanghai',
    destination: 'Shanghai, China',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-04-03',
    endDate: '2026-04-05',
    displayDates: 'Apr 3–5, 2026',
    description: 'The Calling (Silver Age, $20K) + Showdown at The Ritz-Carlton Shanghai, Pudong.',
    link: 'https://fabtcg.com/organised-play/2026/calling-shanghai/',
    reportId: 'calling-shanghai-2026',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-prague-2026',
    title: 'Calling – Prague',
    destination: 'Prague, Czech Republic',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-05-22',
    endDate: '2026-05-24',
    displayDates: 'May 22–24, 2026',
    description: 'Omens of the Third Age World Premiere & Calling (Sealed Deck, $20K) at PVA EXPO PRAHA.',
    link: 'https://fabtcg.com/organised-play/2026/omens-of-the-third-age-world-premiere-prague/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-minneapolis-2026',
    title: 'Calling – Minneapolis',
    destination: 'Minneapolis, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-06-12',
    endDate: '2026-06-14',
    displayDates: 'Jun 12–14, 2026',
    description: 'USA National Championship ($50K) & Calling (Omens Sealed + Draft, $20K) at Minneapolis Convention Center.',
    link: 'https://fabtcg.com/organised-play/2026/united-states-national-championship-2026-calling-minneapolis/',
    tags: ['FaB', 'Calling', 'Nationals', 'World Tour'],
  },

  {
    id: 'fab-nationals-germany-2026',
    title: 'DE Nationals',
    destination: 'Gelsenkirchen, Germany',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-07-04',
    endDate: '2026-07-05',
    displayDates: 'Jul 4–5, 2026',
    description: 'German National Championship at Event Center Kaue, Gelsenkirchen.',
    link: 'https://fabtcg.com/organised-play/2026/national-championship-2026-germany/',
    prepId: 'german-nationals-2026',
    tags: ['FaB', 'Nationals', 'World Tour'],
  },

  {
    id: 'fab-pro-tour-las-vegas-2026',
    title: 'Pro Tour – Las Vegas',
    destination: 'Las Vegas, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-07-16',
    endDate: '2026-07-19',
    displayDates: 'Jul 16–19, 2026',
    description: 'Pro Tour: Las Vegas (Classic Constructed & Set 19 Booster Draft) + Calling at Westgate Las Vegas Resort.',
    link: 'https://fabtcg.com/organised-play/2026/pro-tour-las-vegas/',
    tags: ['FaB', 'Pro Tour', 'World Tour'],
  },

  {
    id: 'fab-calling-shinjuku-2026',
    title: 'Calling – Shinjuku',
    destination: 'Tokyo, Japan',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-07-10',
    endDate: '2026-07-12',
    displayDates: 'Jul 10–12, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Bellesalle Shinjuku Central Park, Tokyo.',
    link: 'https://fabtcg.com/organised-play/2026/calling-shinjuku/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-hamburg-2026',
    title: 'Calling – Hamburg',
    destination: 'Hamburg, Germany',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-08-21',
    endDate: '2026-08-23',
    displayDates: 'Aug 21–23, 2026',
    description: 'The Calling (Classic Constructed, $20K) + Battle Hardened (Living Legend, $2K) in Hamburg.',
    link: 'https://fabtcg.com/organised-play/2026/calling-hamburg-2/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-jakarta-2026',
    title: 'Calling – Jakarta',
    destination: 'Jakarta, Indonesia',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-05-08',
    endDate: '2026-05-10',
    displayDates: 'May 8–10, 2026',
    description: 'The Calling (Classic Constructed + Silver Age) at Townhall, IDD – Indonesia Design District, Tangerang.',
    link: 'https://fabtcg.com/organised-play/2026/calling-jakarta/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-sao-paulo-2026',
    title: 'Calling – São Paulo',
    destination: 'São Paulo, Brazil',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-05-15',
    endDate: '2026-05-17',
    displayDates: 'May 15–17, 2026',
    description: 'The Calling (Classic Constructed + Silver Age, $20K) at Tenis Clube Paulista, São Paulo.',
    link: 'https://fabtcg.com/organised-play/2026/calling-sao-paulo-2/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-auckland-2026',
    title: 'Calling – Auckland',
    destination: 'Auckland, New Zealand',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-06-05',
    endDate: '2026-06-07',
    displayDates: 'Jun 5–7, 2026',
    description: 'The Calling (Classic Constructed, $20K) at JW Marriott Auckland.',
    link: 'https://fabtcg.com/organised-play/2026/calling-auckland-3/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-edinburgh-2026',
    title: 'Calling – Edinburgh',
    destination: 'Edinburgh, UK',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-07-24',
    endDate: '2026-07-26',
    displayDates: 'Jul 24–26, 2026',
    description: 'The Calling (Silver Age + Classic Constructed, $20K) at Edinburgh International Conference Centre.',
    link: 'https://fabtcg.com/organised-play/2026/calling-edinburgh/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-bangkok-2026',
    title: 'Calling – Bangkok',
    destination: 'Bangkok, Thailand',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-08-07',
    endDate: '2026-08-09',
    displayDates: 'Aug 7–9, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Bangkok International Trade & Exhibition Centre (BITEC).',
    link: 'https://fabtcg.com/organised-play/2026/calling-bangkok/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-kansas-city-2026',
    title: 'Calling – Kansas City',
    destination: 'Kansas City, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    displayDates: 'Aug 28–30, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Overland Park Convention Center, Kansas City area.',
    link: 'https://fabtcg.com/organised-play/2026/calling-kansas-city-2/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-seoul-2026',
    title: 'Calling – Seoul',
    destination: 'Seoul, South Korea',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-09-11',
    endDate: '2026-09-13',
    displayDates: 'Sep 11–13, 2026',
    description: 'The Calling (Classic Constructed, $20K) + Set 20 World Premiere at KINTEX 2, Seoul.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-kyoto-2026',
    title: 'Calling – Kyoto',
    destination: 'Kyoto, Japan',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    displayDates: 'Oct 16–18, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Miyako Messe (Kyoto International Exhibition Hall).',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-mexico-city-2026',
    title: 'Calling – Mexico City',
    destination: 'Mexico City, Mexico',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-10-23',
    endDate: '2026-10-25',
    displayDates: 'Oct 23–25, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Expo Reforma, Mexico City.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-world-championship-2026',
    title: 'World Championship',
    destination: 'Paris, France',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-11-05',
    endDate: '2026-11-08',
    displayDates: 'Nov 5–8, 2026',
    description: 'Flesh and Blood World Championship 2026 at Paris Expo Porte de Versailles, France.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Worlds', 'World Tour'],
  },

  {
    id: 'fab-calling-sydney-2026',
    title: 'Calling – Sydney',
    destination: 'Sydney, Australia',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-11-13',
    endDate: '2026-11-15',
    displayDates: 'Nov 13–15, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Club Central Hurstville, Sydney.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-shenzhen-2026',
    title: 'Calling – Shenzhen',
    destination: 'Shenzhen, China',
    region: 'Asia',
    status: 'fab-event',
    startDate: '2026-11-27',
    endDate: '2026-11-29',
    displayDates: 'Nov 27–29, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Crowne Plaza Shenzhen Futian.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-wakefield-2026',
    title: 'Calling – Wakefield',
    destination: 'Wakefield, UK',
    region: 'Europe',
    status: 'fab-event',
    startDate: '2026-12-11',
    endDate: '2026-12-13',
    displayDates: 'Dec 11–13, 2026',
    description: 'The Calling (Classic Constructed, $20K) at WX Wakefield, UK.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

  {
    id: 'fab-calling-portland-2026',
    title: 'Calling – Portland',
    destination: 'Portland, USA',
    region: 'Americas',
    status: 'fab-event',
    startDate: '2026-12-18',
    endDate: '2026-12-20',
    displayDates: 'Dec 18–20, 2026',
    description: 'The Calling (Classic Constructed, $20K) at Hyatt Regency Portland.',
    link: 'https://fabtcg.com/organised-play/',
    tags: ['FaB', 'Calling', 'World Tour'],
  },

];

const TRIPS = [

  // ── PASTE YOUR NEXT TRIP HERE (soonest/newest first) ──────────────────────

  {
    id: 'german-nationals-2026',
    title: 'DE Nationals Weekend',
    destination: 'Gelsenkirchen, Germany',
    region: 'Europe',
    status: 'upcoming',
    startDate: '2026-07-03',
    endDate: '2026-07-06',
    displayDates: 'Jul 3 – 6, 2026',
    description: 'Weekend trip to Gelsenkirchen for the German National Championship (Jul 4–5) at Event Center Kaue. Travelling Friday, events run Saturday–Sunday, home Monday.',
    link: '../trip/?id=german-nationals-2026',
    tags: ['FaB', 'Tournament', 'Europe'],
  },

  {
    id: 'hamburg-2026',
    title: 'The Calling: Hamburg',
    destination: 'Hamburg, Germany',
    region: 'Europe',
    status: 'upcoming',
    startDate: '2026-08-21',
    endDate: '2026-08-24',
    displayDates: 'Aug 21 – 24, 2026',
    description: 'Long weekend in Hamburg for The Calling (Classic Constructed, $20,000 USD) and Battle Hardened (Living Legend, $2,000 USD). Travelling Friday, events run Fri–Sun, home Monday.',
    link: '../trip/?id=hamburg-2026',
    tags: ['FaB', 'Tournament', 'Europe'],
  },

  {
    id: 'prague-omens-2026',
    title: 'Prague – Omens World Premiere',
    destination: 'Prague, Czech Republic',
    region: 'Europe',
    status: 'upcoming',
    startDate: '2026-05-19',
    endDate: '2026-05-25',
    displayDates: 'May 19 – 25, 2026',
    description: 'Week-long trip to Prague for the Omens of the Third Age World Premiere (May 22–24) at PVA EXPO Praha. Three events across the weekend: World Premiere (Fri), The Calling (Sat), and Sunday Showdown (Sun).',
    link: '../trip/?id=prague-omens-2026',
    tags: ['FaB', 'Tournament', 'Europe'],
  },

  {
    id: 'rotterdam-2026-04',
    title: 'Rotterdam Trip',
    destination: 'Rotterdam, Netherlands',
    region: 'Europe',
    status: 'upcoming',
    startDate: '2026-04-24',
    endDate: '2026-04-27',
    displayDates: 'Apr 24 – 27, 2026',
    description: 'Long weekend in Rotterdam. Travelling by car from the Karlsruhe area on Friday 24th. Staying at an Airbnb Friday through Monday – most others check out Sunday, so the extra night (Sun → Mon) is still to be confirmed.',
    link: '../trip/?id=rotterdam-2026',
    tags: ['Leisure', 'Europe', 'FaB'],
  },

  {
    id: 'fab-asia-tour-2026',
    title: 'FAB Asia Tour 2026',
    destination: 'Shanghai & Yokohama',
    region: 'Asia',
    status: 'upcoming',
    startDate: '2026-03-26',
    endDate: '2026-04-14',
    displayDates: 'Mar 26 – Apr 14, 2026',
    description: 'Two-stop Asia tour covering Calling: Shanghai (Apr 3–5) and Pro Tour: Yokohama (Apr 9–12). Frankfurt → Shanghai → Japan → Frankfurt. Day-by-day timeline and booking checklist.',
    link: '../yokohama-pro-tour/',
    tags: ['FaB', 'Tournament'],
  },

];

// Combined array used by calendar.html (includes both trips and FaB World Tour info events)
let ALL_EVENTS = [...TRIPS, ...FAB_WORLD_TOUR];
